services:
  mysql:
    image: 'mysql:8.0'
    container_name: 'mysql'
    environment:
      MYSQL_DATABASE: 'db_usuario'
      MYSQL_PASSWORD: 'abc123'
      MYSQL_ROOT_PASSWORD: 'verysecret'
      MYSQL_USER: 'davi'
    ports:
      - "3307:3306"
    networks:
      - backend
    restart: always
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  api:
    build: .
    container_name: 'api'
    depends_on:
      mysql:
        condition: service_healthy
    ports:
      - "8081:8081"
    networks:
      - backend
    restart: on-failure

networks:
  backend:
    driver: bridge