services:
  mongodb:
    image: mongo:5.0
    container_name: mongo-database
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: userdb
    networks:
      - backend
    healthcheck:
      test: ["CMD", "mongo", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 30s
      retries: 5
      start_period: 40s
    restart: unless-stopped

  api:
    build: .
    container_name: 'mongoapi'
    depends_on:
      mongodb:
        condition: service_healthy
    ports:
      - "8080:8080"
    networks:
      - backend
    restart: on-failure
    environment:
      - MONGO_URI=mongodb://mongo:27017/user

networks:
  backend:
    driver: bridge