version: '3.8'

services:
  mongodb:
    image: mongo:5.0
    container_name: mongo-database
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      MONGO_INITDB_DATABASE: userdb
    healthcheck:
      test: ["CMD", "mongo", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 30s
      retries: 5
      start_period: 40s
    restart: unless-stopped

  app:
    build: .
    container_name: java-app
    ports:
      - "8080:8081"
    depends_on:
      mongodb:
        condition: service_healthy
    environment:
      SPRING_DATA_MONGODB_URI: mongodb://mongo-database:27017/productdb?connectTimeoutMS=10000&socketTimeoutMS=10000&serverSelectionTimeoutMS=10000
      WAIT_HOSTS: mongo-database:27017
      WAIT_HOSTS_TIMEOUT: 300
      WAIT_SLEEP_INTERVAL: 10
      WAIT_HOST_CONNECT_TIMEOUT: 30
    restart: on-failure
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8080/actuator/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  mongodb_data: